### PR TITLE
Use reflection to call SQLContext.createDataFrame

### PR DESCRIPTION
**Pull request by chtyim**
- Spark 1 and Spark 2 are not binary compatible for the method

### CODE REVIEW

**Review by sagarkapare — APPROVED** [review]
LGTM 👍

**Comment by ecfm** [comment]
The spark version in pom is still 1.6.3. Is it supposed to be changed? Or should we test it with Spark 2?

**Comment by chtyim** [comment]
@maochf We still support Spark 1, hence the plugin is compiled with Spark 1. The change is to make the binary also work against Spark 2 at runtime.

**Comment by ecfm** [comment]
Has it been tested with Spark 2?

**Comment by chtyim** [comment]
yes

**Comment by ecfm** [comment]
LGTM

**Pull request merged**
